---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dp-zebedee-sdk-go
    path: dp-zebedee-sdk-go

run:
  path: dp-zebedee-sdk-go/ci/scripts/build.sh